version: '3.9'

services:
  db:
    image: postgres:15
    container_name: cookbook_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env    #tells Docker to read environment variables from .env file  

volumes:
  db_data:
