version: '3.9'

services:
  db:
    image: postgres:15
    container_name: cookbook_db
    restart: always
    environment:
      POSTGRES_USER: cookbook_user
      POSTGRES_PASSWORD: cookbook_pass
      POSTGRES_DB: cookbook_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
